# Generated by Django 3.2.14 on 2022-07-16 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='request',
            name='last_modification_time',
        ),
        migrations.AlterField(
            model_name='request',
            name='status',
            field=models.CharField(choices=[('c', 'Created'), ('a', 'Approved'), ('r', 'Rejected'), ('p', 'Paid')], max_length=1),
        ),
        migrations.CreateModel(
            name='RequestHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modified', models.DateTimeField(auto_now_add=True)),
                ('type_of_change', models.CharField(choices=[('c', 'Created'), ('a', 'Approved'), ('r', 'Rejected'), ('p', 'Paid'), ('e', 'Edited')], max_length=1)),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='api.request')),
            ],
        ),
    ]
