# Generated by Django 3.2.14 on 2022-07-06 19:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(choices=[('cw', 'Common Worker'), ('r', 'Reviewer'), ('a', 'Administrator')], max_length=2, primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(default='cw', on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
    ]
