# Generated by Django 3.2.14 on 2022-07-11 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20220706_1906'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userrole',
            name='role',
            field=models.ForeignKey(default='cw', max_length=2, on_delete=django.db.models.deletion.CASCADE, to='api.role'),
        ),
        migrations.CreateModel(
            name='Request',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('c', 'Created'), ('a', 'Approved'), ('r', 'Rejected'), ('d', 'Done')], max_length=1)),
                ('bonus_type', models.CharField(max_length=80)),
                ('description', models.TextField()),
                ('creation_time', models.DateTimeField(auto_now_add=True)),
                ('last_modification_time', models.DateTimeField(auto_now=True)),
                ('paymant_day', models.DateField(null=True)),
                ('creator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='request_creator', to='api.user')),
                ('reviewer', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_reviewer', to='api.user')),
            ],
        ),
    ]
