# Generated by Django 3.2.14 on 2022-07-12 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_auto_20220711_1720'),
    ]

    operations = [
        migrations.AlterField(
            model_name='request',
            name='reviewer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='request_reviewer', to='api.user'),
        ),
    ]
